
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVMODrightPOWnonassocNEGADD DIV LSB MOD MUL NL NUM POW RSB SUBinput : \n        | input lineline : NLline : exp NLexp : NUMexp : exp ADD expexp : exp SUB expexp : SUB exp %prec NEGexp : exp MUL expexp : exp DIV expexp : LSB exp RSBexp : exp POW expexp : exp MOD exp'
    
_lr_action_items = {'NL':([0,1,2,3,4,5,8,15,17,18,19,20,21,22,23,],[-1,3,-2,-3,8,-5,-4,-8,-6,-7,-9,-10,-12,-13,-11,]),'NUM':([0,1,2,3,6,7,8,9,10,11,12,13,14,],[-1,5,-2,-3,5,5,-4,5,5,5,5,5,5,]),'SUB':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,],[-1,6,-2,-3,10,-5,6,6,-4,6,6,6,6,6,6,-8,10,-6,-7,-9,-10,-12,-13,-11,]),'LSB':([0,1,2,3,6,7,8,9,10,11,12,13,14,],[-1,7,-2,-3,7,7,-4,7,7,7,7,7,7,]),'$end':([0,1,2,3,8,],[-1,0,-2,-3,-4,]),'ADD':([4,5,15,16,17,18,19,20,21,22,23,],[9,-5,-8,9,-6,-7,-9,-10,-12,-13,-11,]),'MUL':([4,5,15,16,17,18,19,20,21,22,23,],[11,-5,-8,11,11,11,-9,-10,-12,-13,-11,]),'DIV':([4,5,15,16,17,18,19,20,21,22,23,],[12,-5,-8,12,12,12,-9,-10,-12,-13,-11,]),'POW':([4,5,15,16,17,18,19,20,21,22,23,],[13,-5,-8,13,13,13,13,13,13,13,-11,]),'MOD':([4,5,15,16,17,18,19,20,21,22,23,],[14,-5,-8,14,14,14,-9,-10,-12,-13,-11,]),'RSB':([5,15,16,17,18,19,20,21,22,23,],[-5,-8,23,-6,-7,-9,-10,-12,-13,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'line':([1,],[2,]),'exp':([1,6,7,9,10,11,12,13,14,],[4,15,16,17,18,19,20,21,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> <empty>','input',0,'p_input','calc.py',75),
  ('input -> input line','input',2,'p_input','calc.py',76),
  ('line -> NL','line',1,'p_line','calc.py',80),
  ('line -> exp NL','line',2,'p_line2','calc.py',84),
  ('exp -> NUM','exp',1,'p_num','calc.py',88),
  ('exp -> exp ADD exp','exp',3,'p_add','calc.py',94),
  ('exp -> exp SUB exp','exp',3,'p_sub','calc.py',100),
  ('exp -> SUB exp','exp',2,'p_usub','calc.py',106),
  ('exp -> exp MUL exp','exp',3,'p_mul','calc.py',112),
  ('exp -> exp DIV exp','exp',3,'p_div','calc.py',118),
  ('exp -> LSB exp RSB','exp',3,'p_brackets','calc.py',124),
  ('exp -> exp POW exp','exp',3,'p_pow','calc.py',128),
  ('exp -> exp MOD exp','exp',3,'p_mod','calc.py',134),
]
